# Laboratorio 1
## Esercizio 6:
Scrivere uno script file per definire i vettori x = (1, 2, 3, 4)T e y = (2, 4, 6, 8)T e calcolare:x + y, xT , xT y e il prodotto componente a componente fra i vettori x e y.

In [39]:
x = [1;2;3;4];
y = [2;4;6;8];


In [40]:
x+y

4-element Vector{Int64}:
  3
  6
  9
 12

In [41]:
x'

1×4 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  3  4

In [42]:
x' * y

60

In [43]:
x .* y

4-element Vector{Int64}:
  2
  8
 18
 32

## Esercizio 7:
Scrivere uno script file per assegnare i seguenti vettori:
- z ∈ IR20 tale che: zk = k, per k = 1, 2, . . . , 20;
- v ∈ IR100 tale che: v1 = 3, vi = 10−3 , i = 2, 3, . . . , 100;
- w ∈ IRn tale che: wk = a + (k − 1)h, per k = 1, 2, . . . , n, con n = 21, a = 0, h = 1/(n − 1).

In [44]:
z = zeros(20);
for k = 1:20
    z[k] = k;
end

z


20-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0
 11.0
 12.0
 13.0
 14.0
 15.0
 16.0
 17.0
 18.0
 19.0
 20.0

In [45]:
v = ones(100) * 10^-3;
v[1] = 3;

v

100-element Vector{Float64}:
 3.0
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001
 ⋮
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001
 0.001

In [46]:
n = 21;
w = ones(n);
a = 0;
h = 1 / (n - 1);
for k = 1:n
    w[k] = (a +(k - 1)*h);
end

w

21-element Vector{Float64}:
 0.0
 0.05
 0.1
 0.15000000000000002
 0.2
 0.25
 0.30000000000000004
 0.35000000000000003
 0.4
 0.45
 ⋮
 0.6000000000000001
 0.65
 0.7000000000000001
 0.75
 0.8
 0.8500000000000001
 0.9
 0.9500000000000001
 1.0

# Esercizio 8


In [47]:
A = [2 2;2 2];
B = [1 2;3 4];
b = [5 ; 6];

In [48]:
A + B

2×2 Matrix{Int64}:
 3  4
 5  6

In [49]:
A - B

2×2 Matrix{Int64}:
  1   0
 -1  -2

In [50]:
A * B

2×2 Matrix{Int64}:
 8  12
 8  12

In [51]:
A .* B

2×2 Matrix{Int64}:
 2  4
 6  8

In [52]:
A * b

2-element Vector{Int64}:
 22
 22

In [53]:
I = identity(2);
C = (A^2).*I

2×2 Matrix{Int64}:
 16  16
 16  16

In [54]:
A * A

2×2 Matrix{Int64}:
 8  8
 8  8

In [55]:
b = [1 ; 1];
x = B \ b;
x

2-element Vector{Float64}:
 -1.0
  1.0